# site
name: 站点名称
description: 站点描述
favicon:
banner: /imgs/head.jpg
rss:  

# navigation
menu:
  主页:
    url: /
    icon: home
    iconType: fa
  归档:
    url: /archives/
    icon: archive
    iconType: fa
  分类:
    url: javascript:void(0)
    icon: folder-open
    iconType: fa
    child:
      分类1:
        url: javascript:void(0)
        icon: category
        iconType: fa
# Social account
account:
  github:
    url: /
    icon: github
    iconType: fa
  mail:
    url: /
    icon: envelope
    iconType: fa
  twitter:
    url: /
    icon: twitter
    iconType: fa

  # Comment system
comment:
  disqus:
    shortname:  
  
  # Features
ifsparticle:  false

# Child theme
childtheme: 0