# site
name: Mokusei
description: 站点描述
favicon:
rss:  

# navigation
menu:
  主页:
    url: /
  归档:
    url: /archives/
  关于:
    url: /about/

# Comment system
comment:
  disqus:
    shortname: shiju

# Slidebar
widgetArticle:
  amount: 5