# site
name: 站点
description: 站点描述
favicon:
rss:  

# img
headerImg: /imgs/header.jpg

# me
meAvatar: /imgs/avatar.jpeg

# account list
accountList:
  github:
    url: /
    icon: github
  facebook:
    url: /
    icon: facebook
  google:
    url: /
    icon: google
  instagram:
    url: /
    icon: instagram
    

# navigation
menu:
  主页:
    url: /
  归档:
    url: /archives/
  关于:
    url: /about/

# Comment system
comment:
  disqus:
    shortname: 

# Slidebar
widgetArticle:
  amount: 5