# 站点相关
name: 站点名称
description: 站点描述
favicon:
banner: http://plo9kpis3.bkt.clouddn.com/head.jpg
rss:  12321

# 导航相关
menu:
  首页:
    url: /
    icon: home
    iconType: fa
  归档:
    url: /archives/
    icon: archive
    iconType: fa

# 社交账户
account:
  github:
    url: /
    icon: github
    iconType: fa
  mail:
    url: /
    icon: envelope
    iconType: fa
  twitter:
    url: /
    icon: twitter
    iconType: fa

  # 评论系统
comment:
  disqus:
    shortname:  shiju


